/** Static markup names actions; typed callbacks own all executable bindings. */
export const APP_ACTION_NAMES = [
  'openUsageView',
  'openSkillsView',
  'openRoutinesView',
  'openSettingsModal',
  'refreshSessions',
  'openNewSessionView',
  'openSessionHarnessSettings',
  'openStatsModal',
  'toggleSearchBar',
  'toggleControlPanel',
  'toggleTerminal',
  'toggleFocusMode',
  'toggleDiffView',
  'openArtifactsModal',
  'exportSession',
  'searchKey',
  'searchPrev',
  'searchNext',
  'closeSearch',
  'loadDiffView',
  'closeDiffView',
  'closeFileView',
  'switchTerminalMode',
  'restartTerminalShell',
  'closeTerminal',
  'resumeSession',
  'panelOpenSearch',
  'panelToggleTerminal',
  'panelOpenDiffView',
  'panelOpenArtifactsModal',
  'panelOpenTreeModal',
  'panelOpenSessionHarnessSettings',
  'panelExportSession',
  'attachImage',
  'abortTurn',
  'sendSteer',
  'sendFollowUp',
  'sendPrompt',
  'loadUsageView',
  'closeUsageView',
  'closeSearchView',
  'closeNewSessionView',
  'onNsHostChange',
  'onNsHarnessChange',
  'onNsModelChange',
  'onNsThinkingChange',
  'editHarnessAgents',
  'editHarnessModels',
  'spawnNewSession',
  'refreshRoutinesView',
  'closeRoutinesView',
  'loadRecoveryView',
  'closeRecoveryView',
  'backdropCloseTreeModal',
  'closeTreeModal',
  'backdropCloseArtifactsModal',
  'closeArtifactsModal',
  'backdropCloseRelationsModal',
  'closeRelationsModal',
  'backdropCloseStatsModal',
  'closeStatsModal',
  'backdropCloseSettingsModal',
  'closeSettingsModal',
  'bounceToggle',
  'refreshBounceView',
  'bounceSelect',
  'bounceClear',
  'submitBounceTargets',
  'backdropCloseHarnessSettings',
  'closeHarnessSettings',
  'harnessTabAgents',
  'harnessTabModels',
  'saveHarnessSettings',
  'backdropCloseResponseDetails',
  'closeResponseDetails',
] as const;
export type AppAction = typeof APP_ACTION_NAMES[number];
export type AppActions = Readonly<Record<AppAction, (event: Event, node: HTMLElement) => unknown>>;
export function createAppBindings(options: { document: Document; actions: AppActions }) {
  const lifetime = new AbortController(); let disposed = false;
  for (const event of ['click', 'change', 'keydown', 'toggle'] as const) {
    for (const node of Array.from(options.document.querySelectorAll<HTMLElement>(`[data-app-${event}]`))) {
      const name = node.getAttribute(`data-app-${event}`);
      const action = APP_ACTION_NAMES.find(action => action === name); if (!action) throw new Error('Unknown app action: ' + name);
      node.addEventListener(event, value => { if (!disposed && node.isConnected) options.actions[action](value, node); }, { signal: lifetime.signal });
    }
  }
  return { dispose() { if (disposed) return; disposed = true; lifetime.abort(); } };
}
