import type * as BrowserApi from '../../src/browser/index.js';
import type * as SharedHelpers from '../../src/browser/shared-helpers.js';

import type { CompleteTerminalProbe, FixtureFeatures, FixtureRegistry, SidebarControlsLog, SidebarQueryLog, SidebarQueryReply, TerminalProbe } from './fixture-contracts.js';
type TranscriptRequest = Parameters<typeof BrowserApi.createTranscript>[0]['request'];
interface TranscriptReply {
  host: Parameters<TranscriptRequest>[0];
  path: Parameters<TranscriptRequest>[1];
  init: Parameters<TranscriptRequest>[2];
  resolve(response: Response): void;
}
type ApiRequest = FixtureFeatures['apiTransport']['request'];
interface ApiReply {
  args: Parameters<ApiRequest>;
  resolve(response: Response): void;
}
type MessageStreamOptions = Parameters<typeof BrowserApi.createMessageStream>[0];
interface StreamTicketReply {
  resolve(ticket: string): void;
  reject(reason?: unknown): void;
}
interface DiagramReply {
  resolve(value: { svg: string }): void;
  reject(reason?: unknown): void;
}
interface MicPermission {
  resolve(stream: MediaStream): void;
  reject(reason?: unknown): void;
}
interface FixtureMediaRecorder extends MediaRecorder {
  finish(text?: string): void;
}






declare global {
  const PiDishBrowser: typeof BrowserApi;
  const PiDishHelpers: typeof SharedHelpers;
  const Terminal: typeof import('@xterm/xterm').Terminal;
  const sessionKey: typeof import('../../src/browser/helper-identity.js').sessionKey;
  const sessionRefKey: typeof import('../../src/browser/helper-identity.js').sessionRefKey;
  const parseSessionKey: typeof import('../../src/browser/helper-identity.js').parseSessionKey;
  const hostSupportsTerminal: typeof import('../../src/browser/helper-identity.js').hostSupportsTerminal;
  const hostDisplayLabel: typeof import('../../src/browser/helper-identity.js').hostDisplayLabel;
  const formatTokens: typeof import('../../src/browser/helper-format.js').formatTokens;
  const THINKING_LEVEL_NAMES: typeof import('../../src/core/helper-models.js').THINKING_LEVEL_NAMES;
  var fixtureApp: FixtureRegistry;
  function fixtureElement<T>(value: T | null | undefined, label: string): T;
  function fixtureInput(value: Element | null | undefined, label: string): HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement;
  function fixtureDetails(value: Element | null | undefined, label: string): HTMLDetailsElement;
  function fixtureLink(value: Element | null | undefined, label: string): HTMLAnchorElement;
  function fixtureTerminalProbe(): CompleteTerminalProbe;
  function fixtureCurrentSession(): NonNullable<FixtureFeatures['sessionState']['currentSession']>;
  interface Window {
    __oldHostPoll: ReturnType<FixtureFeatures['sidebarLists']['load']>;
    __newSessionCwd: string | null;
    restoreSidebarCreate?: FixtureRegistry['ports']['sidebarControls']['create'];
    appActionCalls: Array<(typeof BrowserApi.APP_ACTION_NAMES)[number]>;
    artifactBodiesRead: number;
    assetFirst: Promise<unknown>;
    assetRetry: Promise<unknown>;
    assetSecond: Promise<unknown>;
    bitmapClosed: number;
    bounceSubmission: ReturnType<FixtureFeatures['bounceController']['submit']>;
    cachedTool: HTMLDetailsElement | null;
    chromeClicks: EventListenerOrEventListenerObject[];
    chromeOlder: number;
    closedCommentRow: HTMLElement | null;
    closedRestore: HTMLElement | null;
    closedSave: ReturnType<FixtureFeatures['harnessSettingsController']['save']>;
    commandReplies: ApiReply[];
    configAfterRetired: Record<string, unknown>;
    configBodyWaiting: boolean;
    controlEndpoint: import('../../src/browser/api-client.js').HostEndpoint;
    controlHosts: Record<string, import('../../src/browser/api-client.js').HostEndpoint>;
    controlStorage: Map<string, string>;
    controlsLog: SidebarControlsLog;
    controlsState: ReturnType<typeof BrowserApi.createSessionState>;
    copyCalls: string[];
    customLists: ReturnType<typeof BrowserApi.createSidebarLists>;
    customQuery: ReturnType<typeof BrowserApi.createSidebarQuery>;
    customSidebar: ReturnType<typeof BrowserApi.createSidebarControls>;
    cwdLoads: Array<ReturnType<FixtureFeatures['newSessionController']['directories']['load']>>;
    delayedSelections: (() => void)[];
    deliveryCalls: ApiReply[];
    deliveryEndpoint: import('../../src/browser/api-client.js').HostEndpoint;
    deliveryRestores: unknown[][];
    diagramCalls: DiagramReply[];
    diagramFragment: DocumentFragment;
    diagramRequireBeforeSvg: boolean;
    diagramScrolls: number;
    directoryBodyWaiting: boolean;
    disposedCommand: ReturnType<FixtureFeatures['composerSubmit']['sendPrompt']>;
    disposedHarnessRead: Promise<unknown>;
    disposedInfoBody: string;
    disposedResume: Promise<unknown>;
    disposedStreamStart: Promise<unknown>;
    downloadNames: string[];
    editRequest: ReturnType<FixtureFeatures['promptDelivery']['edit']>;
    exportBlobs: number;
    exportOne: ReturnType<FixtureFeatures['sessionControls']['export']>;
    exportPromise: ReturnType<FixtureFeatures['sessionControls']['export']>;
    exportTwo: ReturnType<FixtureFeatures['sessionControls']['export']>;
    exportedBlobs: Blob[];
    exports: Blob[];
    extensionDeliveryHook: boolean;
    failedTail: Promise<unknown>;
    finalCatchup: Promise<unknown>;
    firstCommand: ReturnType<FixtureFeatures['composerSubmit']['sendPrompt']>;
    firstModel: ReturnType<FixtureFeatures['sessionControls']['selectModel']>;
    firstQueueEdit: ReturnType<FixtureFeatures['promptDelivery']['edit']>;
    firstStreamStart: Promise<unknown>;
    fleetBodiesDecoded: number;
    fleetReadyObserved: boolean;
    frameRenderer: ReturnType<typeof BrowserApi.createStreamingRenderer>;
    frameTexts: unknown[];
    hostBodyWaiting: boolean;
    infoCopies: string[];
    lateExport: ReturnType<FixtureFeatures['sessionControls']['export']>;
    limitReads: number;
    listCalls: number;
    listRefreshes: number;
    micPermissions: MicPermission[];
    micRecorders: FixtureMediaRecorder[];
    micTracks: MediaStreamTrack[];
    micTrackStops: number[];
    modelBodyWaiting: boolean;
    modelLoads: unknown[];
    newAdd: ReturnType<FixtureFeatures['hostSettings']['addFromForm']>;
    newBtw: ReturnType<FixtureFeatures['btwPanel']['show']>;
    newCatchup: Promise<unknown>;
    newDiscovery: Promise<unknown>;
    newIdentity: ReturnType<FixtureFeatures['hostDiscovery']['identify']>;
    newSpawn: ReturnType<FixtureFeatures['newSessionController']['spawn']>;
    newTail: Promise<unknown>;
    oldAdd: ReturnType<FixtureFeatures['hostSettings']['addFromForm']>;
    oldBranch: HTMLElement | null;
    oldBtw: ReturnType<FixtureFeatures['btwPanel']['show']>;
    oldCatchup: Promise<unknown>;
    oldCommands: ReturnType<FixtureFeatures['composerAutocomplete']['loadCommands']>;
    oldComments: ReturnType<FixtureFeatures['anchoredCommentController']['refresh']>;
    oldCompletion: HTMLElement | null;
    oldDelete: ReturnType<FixtureFeatures['anchoredCommentController']['remove']>;
    oldDetails: HTMLDetailsElement | null;
    oldDiagramLabel: HTMLElement | null;
    oldDiagramZoom: HTMLElement | null;
    oldDiscovery: Promise<unknown>;
    oldDismiss: HTMLElement | null;
    oldEndpointStart: Promise<unknown>;
    oldCommentRow: HTMLElement | null;
    oldFilterDelete: HTMLElement | null;
    oldIdentity: ReturnType<FixtureFeatures['hostDiscovery']['identify']>;
    oldLineageRow: HTMLElement | null;
    oldLink: HTMLElement | null;
    oldMenuButton: HTMLElement | null;
    oldNavigationSearch: ReturnType<FixtureFeatures['sessionSearch']['run']>;
    oldFile: ReturnType<FixtureFeatures['fileViews']['openFile']>;
    oldPagingButton: HTMLElement | null;
    oldPicker: Promise<unknown>;
    oldQueueEdit: HTMLElement | null;
    oldRange: HTMLElement | null;
    oldRecoverySave: HTMLButtonElement | null;
    oldRelationLink: HTMLElement | null;
    oldRemove: HTMLElement | null;
    oldResumeModels: ReturnType<FixtureFeatures['sessionResume']['load']>;
    oldRevoke: HTMLElement | null;
    oldRow: HTMLElement | null;
    oldScopeButton: HTMLElement | null;
    oldSettings: ReturnType<FixtureFeatures['harnessSettingsController']['open']>;
    oldSideClose: HTMLElement | null;
    oldSpawn: ReturnType<FixtureFeatures['newSessionController']['spawn']>;
    oldPage: ReturnType<ReturnType<typeof BrowserApi.createTranscript>['loadOlder']>;
    oldTail: Promise<unknown>;
    oldTokenRestore: HTMLElement | null;
    oldTranscription: ReturnType<FixtureFeatures['composerSpeech']['transcribe']>;
    oldUsageBar: HTMLElement | null;
    oldUsageModel: HTMLElement | null;
    oldUsageSession: HTMLElement | null;
    oldDayClose: HTMLElement | null;
    oldWidget: HTMLElement | null;
    oldWorkspaceButton: HTMLElement | null;
    openingFile: ReturnType<FixtureFeatures['fileViews']['openFile']>;
    ownedBindings: ReturnType<typeof BrowserApi.createAppBindings>;
    ownedChrome: ReturnType<typeof BrowserApi.createAppChrome>;
    ownedDelivery: ReturnType<typeof BrowserApi.createPromptDelivery>;
    ownedResume: ReturnType<typeof BrowserApi.createSessionResume>;
    ownedStream: ReturnType<typeof BrowserApi.createMessageStream>;
    ownedTranscript: ReturnType<typeof BrowserApi.createTranscript>;
    patchPromise: ReturnType<FixtureFeatures['fileViews']['loadPatch']>;
    peerDialog: HTMLElement | null;
    peerWorkspaceButton: HTMLElement | null;
    pendingAdd: ReturnType<FixtureFeatures['hostSettings']['addFromForm']>;
    pendingBranch: ReturnType<FixtureFeatures['transcriptTree']['confirm']>;
    pendingCommentFocus: ReturnType<FixtureFeatures['anchoredCommentController']['focus']>;
    pendingIdentity: ReturnType<FixtureFeatures['hostDiscovery']['identify']>;
    pendingMic: ReturnType<FixtureFeatures['composerSpeech']['start']>;
    pendingResume: ReturnType<FixtureFeatures['sessionResume']['resume']>;
    pendingSearchNavigation: ReturnType<FixtureFeatures['searchViewController']['openResult']>;
    pendingSessionSearch: ReturnType<FixtureFeatures['sessionSearch']['run']>;
    pendingShareCopy: ReturnType<FixtureFeatures['sessionInfo']['copyMessage']>;
    pendingSkillDetail: ReturnType<FixtureFeatures['skillsController']['detail']>;
    pendingThinking: ReturnType<FixtureFeatures['sessionControls']['selectThinking']>;
    pendingTree: ReturnType<FixtureFeatures['transcriptTree']['open']>;
    pickerDiscovery: Promise<unknown>;
    queryEndpoint: import('../../src/browser/api-client.js').HostEndpoint;
    queryLog: SidebarQueryLog;
    queryReplies: SidebarQueryReply[];
    queryStore: Map<string, string>;
    queueCancels: ApiReply[];
    recoveryBodyWaiting: boolean;
    replacedRemove: HTMLElement | null;
    replacementFleetLoad: ReturnType<FixtureFeatures['hostDiscovery']['loadFleet']>;
    resumeCalls: ApiReply[];
    resumeEffects: unknown[];
    resumeEndpoint: import('../../src/browser/api-client.js').HostEndpoint;
    resumeFirst: Promise<unknown>;
    resumeNavigations: unknown[];
    resumeResponses: ApiReply[];
    resumeStatuses: unknown[];
    retainedSelectionMessage: HTMLElement | null;
    retiredBounceCancel: HTMLElement | null;
    retiredBounceInput: HTMLInputElement | null;
    retiredFacet: HTMLElement | null;
    retiredRestore: HTMLElement | null;
    retiredSearchCard: HTMLElement | null;
    retiredSearchFacet: HTMLElement | null;
    retiredSkillRow: HTMLElement | null;
    retiredSkillsRefresh: HTMLElement | null;
    retiredTail: Promise<unknown>;
    retiredTargetRow: HTMLElement | null;
    retiredTreeRow: HTMLElement | null;
    revokedExports: string[];
    rt: ReturnType<typeof BrowserApi.createRoutinesView>;
    secondCommand: ReturnType<FixtureFeatures['composerSubmit']['sendPrompt']>;
    secondModel: ReturnType<FixtureFeatures['sessionControls']['selectModel']>;
    secondStreamStart: Promise<unknown>;
    selfAbort: ReturnType<FixtureFeatures['composerSubmit']['abortTurn']>;
    shareCopy: ReturnType<FixtureFeatures['sessionInfo']['copyMessage']>;
    sideQuestion: ReturnType<typeof BrowserApi.createBtwPanel>;
    staleSelection: ReturnType<FixtureFeatures['sessionState']['captureSelection']>;
    startupMounted: boolean;
    streamEndpoint: import('../../src/browser/api-client.js').HostEndpoint;
    streamLoads: Array<() => void>;
    streamSelections: Array<Parameters<MessageStreamOptions['select']>>;
    streamSources: EventSource[];
    streamStatus: Array<Parameters<MessageStreamOptions['status']>>;
    streamTickets: StreamTicketReply[];
    targetBodyWaiting: boolean;
    targetLoads: Array<ReturnType<FixtureFeatures['newSessionController']['targets']['load']>>;
    termProbe: TerminalProbe;
    testAssets: ReturnType<typeof BrowserApi.createBrowserAssets>;
    testDiagrams: ReturnType<typeof BrowserApi.createDiagrams>;
    testUsage: ReturnType<typeof BrowserApi.createUsageView>;
    thinkingFixtureCalls: unknown[];
    transcriptHosts: Record<string, { base: string }>;
    transcriptLoad: Promise<unknown>;
    transcriptReplies: TranscriptReply[];
    treeBranch: ReturnType<FixtureFeatures['transcriptTree']['confirm']>;
    treeLoad: ReturnType<FixtureFeatures['transcriptTree']['open']>;
    workspaceSpawn: ReturnType<FixtureFeatures['newSessionController']['create']>;
    fixtureSessionListPatch(id: string, fields: Record<string, unknown>, host?: string | null): void;
    emitOwnedStream(index: number, type: string, value: unknown): void;
    fixtureDiagram: HTMLElement;
    routineHosts: import('../../src/browser/routines-view.js').RoutineHost[];
    oldSave: Promise<unknown>;
    heldConfig: Promise<unknown>;
    imagePending: Promise<unknown>;
    deliveryEdit: Promise<unknown>;
    newPage: Promise<unknown>;
    retainedTelemetry: HTMLElement | null;
    oldFilterRead: Promise<unknown>;
    oldScopeRead: Promise<unknown>;
    newFilterWrite: Promise<unknown>;
    saveScope: Promise<unknown>;
    backgroundDiscovery: Promise<unknown>;
    pendingControlClose: Promise<unknown>;
    pendingMenu: Promise<unknown>;
    pendingMutation: Promise<unknown>;
    pendingStreamTicket: Promise<unknown>;
    testSend: Promise<unknown>;
    headerMenu: Promise<unknown>;
    peerSubmit: HTMLElement | null;
    oldWidgetHeader: HTMLElement | null;
    oldPatch: HTMLElement | null;
    oldArtifacts: HTMLElement[];
    oldConfirm: HTMLElement[];
    oldDisplayControls: (HTMLElement | null)[];
    oldInfoControls: HTMLElement[];
    oldRoutineControls: HTMLElement[];
    retiredExtensionButtons: HTMLElement[];
    resolveMic(index: number): void;
    finishBitmap(): Promise<void>;
    finishImage(): Promise<void>;
    finishCopy(): void;
    finishRichCopy(): void;
    finishCloseRequest(value: Response): void;
    finishDisposedCommand(value: Response): void;
    finishHeaderCatalog(): void;
    finishOldLimits(value: unknown): void;
    finishResumeModels(value: Response): void;
    finishRoutineLookup(): void;
    finishSideCopy(): void;
    resolveTranscript(): void;
    restoreRoutineLookup(): void;
    releaseCommentPatch(): void;
    releaseConfigBody(): void;
    releaseDirectoryBody(): void;
    releaseHostBody(): void;
    releaseMenuCatalog(): void;
    releaseModelBody(): void;
    releaseRecoveryBody(): void;
    releaseSearchLoad(): void;
    releaseTargetBody(): void;
    thinkingFixture: ReturnType<typeof BrowserApi.mountThinkingSelector>;
    extensionDelivery: unknown;
    assetsSame: boolean;
    oldDiagramText: string | null;
    routineHostRemoved: string | null;
    richInjected: string;
    treeInjected: string;
    __auditEnabledBody: Record<string, unknown>;
    __auditFailedPrompt: Promise<unknown>;
    __auditFailedPromptId: string | undefined;
    __auditFontLoadDescriptor: PropertyDescriptor | undefined;
    __auditNativeWebSocket: typeof WebSocket;
    __auditOldCatchup: Promise<unknown>;
    __auditOldDiff: Promise<unknown>;
    __auditOldFile: Promise<unknown>;
    __auditQueueAssociation: string | undefined;
    __auditQueueEdit: Promise<unknown>;
    __auditQueuedFirst: HTMLElement;
    __auditQueuedSecond: HTMLElement;
    __auditRealApiFetch: FixtureFeatures['apiTransport']['request'];
    __auditRealFetch: typeof fetch;
    __auditRemainingQueueAssociation: string | undefined;
    __auditSelectionA: Promise<unknown>;
    __auditTerminalA: Promise<unknown>;
    __auditTerminalB: Promise<unknown>;
    __auditTerminalUrls: string[];
    __collisionMutation: Promise<unknown>;
    __rejectAuditPrompt(): void;
    __releaseAuditCatchup(): void;
    __releaseAuditDiff(): void;
    __releaseAuditFile(): void;
    __releaseAuditFonts(): void;
    __releaseAuditPatch(): void;
    __releaseAuditSelection(): void;
    __releaseAuditStats(): void;
    __resolveAuditQueueEdit(): void;
  }
}

export {};
