#!/usr/bin/env node
/**
 * Builds public/vendor/ from node_modules so the frontend has zero CDN
 * dependencies (phones on the LAN may not have internet; a missing CDN
 * script used to silently disable markdown rendering).
 *
 *   node scripts/build-vendor.js
 *
 * Outputs:
 *   public/vendor/marked.min.js      — copied from the marked package
 *   public/vendor/highlight.js      — highlight.js common-languages bundle,
 *                                      built with esbuild
 *                                      (the npm package ships no browser build)
 *   public/vendor/hljs-theme.min.css — highlight.js theme (solarized dark,
 *                                      matching the app palette)
 *   public/vendor/fonts/*.woff2     — modern KaTeX fonts only
 *   public/vendor/xterm.js           — @xterm/xterm UMD build (browser terminal)
 *   public/vendor/xterm.css          — its stylesheet
 *   public/vendor/xterm-addon-fit.js — @xterm/addon-fit UMD build
 *   public/vendor/mermaid.min.js     — mermaid IIFE build (diagram rendering,
 *                                      loaded lazily on the first diagram)
 */
import fs = require('fs');
import path = require('path');
import esbuild = require('esbuild');

const root = path.join(__dirname, '..');
const outDir = path.join(root, 'public', 'vendor');
fs.mkdirSync(outDir, { recursive: true });

// --- marked: ships a browser UMD build, just copy it ---
fs.copyFileSync(
  path.join(root, 'node_modules', 'marked', 'marked.min.js'),
  path.join(outDir, 'marked.min.js'),
);

// --- katex: copy browser bundle, css, and fonts ---
fs.copyFileSync(
  path.join(root, 'node_modules', 'katex', 'dist', 'katex.min.js'),
  path.join(outDir, 'katex.min.js'),
);
const katexCss = fs.readFileSync(
  path.join(root, 'node_modules', 'katex', 'dist', 'katex.min.css'), 'utf8')
  .replace(/,url\(([^)]*\.woff)\) format\("woff"\),url\(([^)]*\.ttf)\) format\("truetype"\)/g, '');
fs.writeFileSync(path.join(outDir, 'katex.min.css'), katexCss);
const fontsIn = path.join(root, 'node_modules', 'katex', 'dist', 'fonts');
const fontsOut = path.join(outDir, 'fonts');
// Remove fallback formats left by an older build; modern supported browsers
// use WOFF2, so packaging WOFF and TTF triples build size for no runtime gain.
fs.rmSync(fontsOut, { recursive: true, force: true });
fs.mkdirSync(fontsOut, { recursive: true });
for (const font of fs.readdirSync(fontsIn)) {
  if (font.endsWith('.woff2')) fs.copyFileSync(path.join(fontsIn, font), path.join(fontsOut, font));
}

// --- mermaid: dist/mermaid.min.js is a self-contained IIFE that assigns
// globalThis.mermaid (the .esm build splits into chunks that a plain <script>
// can't resolve). 3.5MB, so app.js loads it lazily on the first diagram. ---
fs.copyFileSync(
  path.join(root, 'node_modules', 'mermaid', 'dist', 'mermaid.min.js'),
  path.join(outDir, 'mermaid.min.js'),
);

// --- xterm.js: ships browser UMD builds, just copy them ---
fs.copyFileSync(
  path.join(root, 'node_modules', '@xterm', 'xterm', 'lib', 'xterm.js'),
  path.join(outDir, 'xterm.js'),
);
fs.copyFileSync(
  path.join(root, 'node_modules', '@xterm', 'xterm', 'css', 'xterm.css'),
  path.join(outDir, 'xterm.css'),
);
fs.copyFileSync(
  path.join(root, 'node_modules', '@xterm', 'addon-fit', 'lib', 'addon-fit.js'),
  path.join(outDir, 'xterm-addon-fit.js'),
);

// --- highlight.js theme css ---
fs.copyFileSync(
  path.join(root, 'node_modules', 'highlight.js', 'styles', 'base16', 'solarized-dark.min.css'),
  path.join(outDir, 'hljs-theme.min.css'),
);

// --- highlight.js: bundle the common languages as one local browser script ---
const hljsPkg: Record<string, unknown> = require(path.join(root, 'node_modules', 'highlight.js', 'package.json'));
const hljsLicense = fs.readFileSync(
  path.join(root, 'node_modules', 'highlight.js', 'LICENSE'), 'utf-8').trim();
esbuild.buildSync({
  absWorkingDir: root,
  stdin: { contents: "window.hljs = require('highlight.js/lib/common');", resolveDir: root },
  bundle: true,
  platform: 'browser',
  format: 'iife',
  target: 'es2022',
  outfile: path.join(outDir, 'highlight.js'),
  banner: { js: `/* highlight.js common bundle — generated by scripts/build-vendor.js */\n/*!\nhighlight.js v${hljsPkg.version}\nhttps://github.com/highlightjs/highlight.js\n\n${hljsLicense}\n*/` },
});
console.log('vendor bundle written: hljs common languages, marked, katex (woff2), xterm, mermaid, hljs theme css');
