#!/usr/bin/env node
/**
 * Builds public/vendor/ from node_modules so the frontend has zero CDN
 * dependencies (phones on the LAN may not have internet; a missing CDN
 * script used to silently disable markdown rendering).
 *
 *   node scripts/build-vendor.js
 *
 * Outputs:
 *   public/vendor/marked.min.js      — copied from the marked package
 *   public/vendor/highlight.js      — highlight.js common-languages bundle,
 *                                      built with a minimal CJS wrapper
 *                                      (the npm package ships no browser build)
 *   public/vendor/hljs-theme.min.css — highlight.js theme (solarized dark,
 *                                      matching the app palette)
 *   public/vendor/xterm.js           — @xterm/xterm UMD build (browser terminal)
 *   public/vendor/xterm.css          — its stylesheet
 *   public/vendor/xterm-addon-fit.js — @xterm/addon-fit UMD build
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const outDir = path.join(root, 'public', 'vendor');
fs.mkdirSync(outDir, { recursive: true });

// --- marked: ships a browser UMD build, just copy it ---
fs.copyFileSync(
  path.join(root, 'node_modules', 'marked', 'marked.min.js'),
  path.join(outDir, 'marked.min.js'),
);

// --- xterm.js: ships browser UMD builds, just copy them ---
fs.copyFileSync(
  path.join(root, 'node_modules', '@xterm', 'xterm', 'lib', 'xterm.js'),
  path.join(outDir, 'xterm.js'),
);
fs.copyFileSync(
  path.join(root, 'node_modules', '@xterm', 'xterm', 'css', 'xterm.css'),
  path.join(outDir, 'xterm.css'),
);
fs.copyFileSync(
  path.join(root, 'node_modules', '@xterm', 'addon-fit', 'lib', 'addon-fit.js'),
  path.join(outDir, 'xterm-addon-fit.js'),
);

// --- highlight.js theme css ---
fs.copyFileSync(
  path.join(root, 'node_modules', 'highlight.js', 'styles', 'base16', 'solarized-dark.min.css'),
  path.join(outDir, 'hljs-theme.min.css'),
);

// --- highlight.js: bundle lib/common.js (CJS, relative requires only) ---
const hljsLib = path.join(root, 'node_modules', 'highlight.js', 'lib');
const modules = new Map(); // absolute path -> source

function collect(file) {
  if (modules.has(file)) return;
  const src = fs.readFileSync(file, 'utf-8');
  modules.set(file, src);
  for (const m of src.matchAll(/require\(['"](\.[^'"]+)['"]\)/g)) {
    let dep = path.resolve(path.dirname(file), m[1]);
    if (!dep.endsWith('.js')) dep += '.js';
    collect(dep);
  }
}
const entry = path.join(hljsLib, 'common.js');
collect(entry);

const id = (file) => JSON.stringify(path.relative(hljsLib, file));
const hljsPkg = require(path.join(root, 'node_modules', 'highlight.js', 'package.json'));
const hljsLicense = fs.readFileSync(
  path.join(root, 'node_modules', 'highlight.js', 'LICENSE'), 'utf-8').trim();
let out = '/* highlight.js common bundle — generated by scripts/build-vendor.js */\n';
out += `/*!\nhighlight.js v${hljsPkg.version}\nhttps://github.com/highlightjs/highlight.js\n\n${hljsLicense}\n*/\n`;
out += '(function(){\nvar __mods = {};\nvar __cache = {};\n';
out += 'function __req(base, rel){\n';
out += '  var parts = (base + "/../" + rel).split("/");\n';
out += '  var stack = [];\n';
out += '  for (var i = 0; i < parts.length; i++) {\n';
out += '    if (parts[i] === "." || parts[i] === "") continue;\n';
out += '    else if (parts[i] === "..") stack.pop();\n';
out += '    else stack.push(parts[i]);\n';
out += '  }\n';
out += '  var key = stack.join("/");\n';
out += '  if (!/\\.js$/.test(key)) key += ".js";\n';
out += '  if (__cache[key]) return __cache[key].exports;\n';
out += '  if (!__mods[key]) throw new Error("module not found: " + key);\n';
out += '  var mod = { exports: {} };\n';
out += '  __cache[key] = mod;\n';
out += '  __mods[key](mod, mod.exports, function(r){ return __req(key, r); });\n';
out += '  return mod.exports;\n';
out += '}\n';
for (const [file, src] of modules) {
  out += `__mods[${id(file)}] = function(module, exports, require){\n${src}\n};\n`;
}
out += `window.hljs = __req(".", ${id(entry)});\n`;
out += '})();\n';

fs.writeFileSync(path.join(outDir, 'highlight.js'), out);
console.log(`vendor bundle written: ${modules.size} hljs modules, marked, hljs theme css`);
