#!/usr/bin/env node
/**
 * Builds public/vendor/ from pinned packages so the frontend has zero CDN
 * dependencies. Build mode replaces only owned outputs; --check compiles into
 * a temporary tree and rejects missing, stale, wrong-mode or orphaned output.
 *
 *   node scripts/build-vendor.js [--check]
 */
import fs = require('node:fs');
import os = require('node:os');
import path = require('node:path');
import esbuild = require('esbuild');

const root = path.join(__dirname, '..');
const targetDir = path.join(root, 'public', 'vendor');
const check = process.argv.includes('--check');
if (process.argv.slice(2).some(arg => arg !== '--check')) {
  throw new Error('Usage: node scripts/build-vendor.js [--check]');
}
const temporaryRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'pi-dish-vendor-'));
const outDir = path.join(temporaryRoot, 'vendor');
const ownedTopLevel = [
  'highlight.js',
  'hljs-theme.min.css',
  'katex.min.css',
  'katex.min.js',
  'marked.min.js',
  'mermaid.min.js',
  'xterm-addon-fit.js',
  'xterm.css',
  'xterm.js',
] as const;

function copyPackage(source: string, output: string): void {
  fs.copyFileSync(path.join(root, 'node_modules', source), path.join(outDir, output));
}

function outputFiles(directory: string): string[] {
  return fs.readdirSync(directory, { recursive: true, withFileTypes: true })
    .filter(entry => entry.isFile())
    .map(entry => path.relative(directory, path.join(entry.parentPath, entry.name)).split(path.sep).join('/'))
    .sort();
}

try {
  fs.mkdirSync(path.join(outDir, 'fonts'), { recursive: true });

  copyPackage('marked/marked.min.js', 'marked.min.js');
  copyPackage('katex/dist/katex.min.js', 'katex.min.js');
  const katexCss = fs.readFileSync(path.join(root, 'node_modules', 'katex', 'dist', 'katex.min.css'), 'utf8')
    .replace(/,url\(([^)]*\.woff)\) format\("woff"\),url\(([^)]*\.ttf)\) format\("truetype"\)/g, '');
  fs.writeFileSync(path.join(outDir, 'katex.min.css'), katexCss);
  const fontsIn = path.join(root, 'node_modules', 'katex', 'dist', 'fonts');
  for (const font of fs.readdirSync(fontsIn)) {
    if (font.endsWith('.woff2')) fs.copyFileSync(path.join(fontsIn, font), path.join(outDir, 'fonts', font));
  }

  copyPackage('mermaid/dist/mermaid.min.js', 'mermaid.min.js');
  copyPackage('@xterm/xterm/lib/xterm.js', 'xterm.js');
  copyPackage('@xterm/xterm/css/xterm.css', 'xterm.css');
  copyPackage('@xterm/addon-fit/lib/addon-fit.js', 'xterm-addon-fit.js');
  copyPackage('highlight.js/styles/base16/solarized-dark.min.css', 'hljs-theme.min.css');

  const hljsPkg: Record<string, unknown> = require(path.join(root, 'node_modules', 'highlight.js', 'package.json'));
  const hljsLicense = fs.readFileSync(path.join(root, 'node_modules', 'highlight.js', 'LICENSE'), 'utf8').trim();
  esbuild.buildSync({
    absWorkingDir: root,
    stdin: { contents: "window.hljs = require('highlight.js/lib/common');", resolveDir: root },
    bundle: true,
    platform: 'browser',
    format: 'iife',
    target: 'es2022',
    outfile: path.join(outDir, 'highlight.js'),
    banner: { js: `/* highlight.js common bundle — generated by scripts/build-vendor.js */\n/*!\nhighlight.js v${hljsPkg.version}\nhttps://github.com/highlightjs/highlight.js\n\n${hljsLicense}\n*/` },
  });

  const expected = outputFiles(outDir);
  const expectedTopLevel = expected.filter(file => !file.includes('/'));
  if (expectedTopLevel.length !== ownedTopLevel.length
      || expectedTopLevel.some((file, index) => file !== [...ownedTopLevel].sort()[index])) {
    throw new Error(`Vendor output mapping mismatch: ${expectedTopLevel.join(', ')}`);
  }
  const actualFonts = fs.existsSync(path.join(targetDir, 'fonts'))
    ? outputFiles(path.join(targetDir, 'fonts')).map(file => `fonts/${file}`) : [];
  const orphaned = actualFonts.filter(file => !expected.includes(file));
  const stale: string[] = [];
  for (const file of expected) {
    const generated = path.join(outDir, file);
    const target = path.join(targetDir, file);
    if (!fs.existsSync(target) || !fs.readFileSync(target).equals(fs.readFileSync(generated))
        || (fs.statSync(target).mode & 0o777) !== 0o644) stale.push(`public/vendor/${file}`);
  }

  if (check) {
    if (stale.length || orphaned.length) {
      throw new Error(`Vendor output mismatch; stale: ${stale.join(', ')}; orphaned: ${orphaned.map(file => `public/vendor/${file}`).join(', ')}`);
    }
    console.log(`Vendor outputs match (${expected.length} files).`);
  } else {
    fs.mkdirSync(targetDir, { recursive: true });
    fs.rmSync(path.join(targetDir, 'fonts'), { recursive: true, force: true });
    for (const file of expected) {
      const target = path.join(targetDir, file);
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.copyFileSync(path.join(outDir, file), target);
      fs.chmodSync(target, 0o644);
    }
    console.log(`Vendor bundle written (${expected.length} files): hljs, marked, katex, xterm and mermaid.`);
  }
} finally {
  fs.rmSync(temporaryRoot, { recursive: true, force: true });
}
